format = """$directory$git_branch$python[>>>](green) """
add_newline = false
scan_timeout = 10
command_timeout = 50

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
use_os_path_sep = false
style = "cyan"
format = "[ $path]($style)$read_only "

[git_branch]
format = "[ $branch](bold purple) "

[python]
format = '[(\($virtualenv\) )](yellow)'
